export const getTokenTest = {
  tkn: "eyJhbGciOiJIUzM4NCJ9.eyJpc3MiOiJBc29tdW5pY2lwaW9zIiwic3ViIjoiQWNjZXNzVG9rZW4iLCJhdWQiOiJyaWdvcmlvc2hAZ21haWwuY29tIiwiZXhwIjoxNjc2OTk4OTgwNDUzLCJuYmYiOjE2NzY5OTUzODAsImlhdCI6MTY3Njk5NTM4MCwibmljayI6IjE4MTI5MTY0IiwianRpIjoiOTMwOWMwZDQtMWQyMC00MDIyLTgxM2UtNDk0MTRmYTUwNWYxIn0.AR40HHKMWE_GExXJfckQJi91D4EI0_3nM7hwKCbozT10dPJhzk1DL9lXK9Qqy34e",
  tiempoExpiracion: 3600000,
};
export const loginUserTest = {
  resultado: {
    usuario: {
      numeroCelular: "1234567891",
      image: "/path/to/imagen",
      estado: "A",
      idUsuario: 1,
      roles: [
        {
          idRol: 1,
          estado: "A",
          nombreRol: "Administrador",
          fechaCreacion: 1636300566000,
          permisos: [
            {
              insertar: true,
              eliminar: false,
              actualizar: true,
              idPermiso: 1,
              consultar: true,
              moduloDominio: {
                descripcionValor: "Módulo Administrador de Usuarios",
                idValorLista: 2,
                valor: "MADM",
                nombreLista: "MODULO",
                valorPadre: null,
              },
            },
            {
              insertar: true,
              eliminar: false,
              actualizar: true,
              idPermiso: 2,
              consultar: true,
              moduloDominio: {
                descripcionValor: "Modulo de Revisión de Solicitudes",
                idValorLista: 4,
                valor: "MRSC",
                nombreLista: "MODULO",
                valorPadre: null,
              },
            },
          ],
        },
      ],
      nombreUsuario: "davids",
      nombre: "David Steven",
      tipoDocumento: "CC",
      ultimaFechaLogin: 1604701850000,
      apellido: "Torres Figueroa",
      fechaCreacion: 1604701850000,
      contrasena: "",
      tipoUsuario: "I",
      numeroDocumento: "1587411224",
      email: "davids182009@gmail.com",
    },
  },
};
export const getTiposDocumentoTest = {
  resultado: {
    dominios: [
      {
        descripcionValor: "Cedula de ciudadanía",
        idValorLista: 1,
        valor: "CC",
        nombreLista: "TIPO_DOCUMENTO",
      },
      {
        descripcionValor: "Cédula de extranjería",
        idValorLista: 6,
        valor: "CE",
        nombreLista: "TIPO_DOCUMENTO",
      },
      {
        descripcionValor: "Pasaporte",
        idValorLista: 7,
        valor: "PA",
        nombreLista: "TIPO_DOCUMENTO",
      },
    ],
  },
};

export const paginadoTest = {
  resultado: {
    paginacion: {
      paginaActual: 0,
      totalPaginas: 10,
      totalRegistros: 117,
    },
    solicitudes: [
      {
        estado: "Radicado",
        nombreTramite: "Solicitud Certificado Catastral",
        idSolicitud: 7,
        tipoTramite: "Solicitudes / Certificados",
        numeroRadicado: "123456789",
      },
      {
        estado: "Radicado",
        nombreTramite: "Solicitud Certificado Catastral",
        idSolicitud: 8,
        tipoTramite: "Solicitudes / Certificados",
        numeroRadicado: "123456789",
      },
      {
        estado: "Radicado",
        nombreTramite: "Solicitud Certificado Catastral",
        idSolicitud: 9,
        tipoTramite: "Solicitudes / Certificados",
        numeroRadicado: "123456789",
      },
      {
        estado: "Radicado",
        nombreTramite: "Solicitud Certificado Catastral",
        idSolicitud: 10,
        tipoTramite: "Solicitudes / Certificados",
        numeroRadicado: "123456789",
      },
      {
        estado: "Radicado",
        nombreTramite: "Solicitud Certificado Catastral",
        idSolicitud: 18,
        tipoTramite: "Solicitudes / Certificados",
        numeroRadicado: "123456789",
      },
      {
        estado: "Radicado",
        nombreTramite: "Solicitud Certificado Catastral",
        idSolicitud: 19,
        tipoTramite: "Solicitudes / Certificados",
        numeroRadicado: "123456789",
      },
      {
        estado: "Radicado",
        nombreTramite: "Solicitud Certificado Catastral",
        idSolicitud: 20,
        tipoTramite: "Solicitudes / Certificados",
        numeroRadicado: "123456789",
      },
      {
        estado: "Radicado",
        nombreTramite: "Solicitud Certificado Catastral",
        idSolicitud: 22,
        tipoTramite: "Solicitudes / Certificados",
        numeroRadicado: "123456789",
      },
      {
        estado: "Radicado",
        nombreTramite: "Solicitud Certificado Catastral",
        idSolicitud: 23,
        tipoTramite: "Solicitudes / Certificados",
        numeroRadicado: "123456789",
      },
      {
        estado: "Radicado",
        nombreTramite: "Solicitud Certificado Catastral",
        idSolicitud: 24,
        tipoTramite: "Solicitudes / Certificados",
        numeroRadicado: "123456789",
      },
    ],
  },
};
export const getUsersTest = {
  resultado: {
    users: [
      {
        numeroCelular: "3101111111",
        estado: "A",
        roles: [
          {
            idRol: 2,
            estado: "A",
            nombreRol: "Usuario_Externo",
            fechaCreacion: "2021-11-07 10:56:06.0",
          },
        ],
        idUsuario: 21,
        nombreUsuario: "123456",
        nombre: "Ana",
        tipoDocumento: "CC",
        apellido: "Diaz",
        fechaCreacion: "2021-12-05 15:52:06.987",
        contrasena: "",
        tipoUsuario: "E",
        numeroDocumento: "123456",
        email: "df@sdf.sdf",
      },
      {
        numeroCelular: "3105454546",
        estado: "A",
        roles: [
          {
            idRol: 2,
            estado: "A",
            nombreRol: "Usuario_Externo",
            fechaCreacion: "2021-11-07 10:56:06.0",
          },
        ],
        idUsuario: 12,
        nombreUsuario: "1234567891",
        nombre: "Rigo",
        tipoDocumento: "CC",
        apellido: "Rios",
        fechaCreacion: "2021-11-15 06:47:48.025",
        contrasena: "",
        tipoUsuario: "E",
        numeroDocumento: "1234567891",
        email: "dfdgfgdgfdg@sfdf.com",
      },
      {
        numeroCelular: "3106334692",
        estado: "A",
        roles: [
          {
            idRol: 2,
            estado: "A",
            nombreRol: "Usuario_Externo",
            fechaCreacion: "2021-11-07 10:56:06.0",
          },
        ],
        idUsuario: 27,
        nombreUsuario: "1022343061",
        nombre: "Juan Carlos",
        tipoDocumento: "CC",
        apellido: "Melo",
        fechaCreacion: "2021-12-09 14:04:48.59",
        contrasena: "",
        tipoUsuario: "E",
        numeroDocumento: "1022343061",
        email: "civil.melo@gmail.com",
      },
      {
        numeroCelular: "3106888888",
        estado: "A",
        roles: [
          {
            idRol: 2,
            estado: "A",
            nombreRol: "Usuario_Externo",
            fechaCreacion: "2021-11-07 10:56:06.0",
          },
        ],
        idUsuario: 29,
        nombreUsuario: "55555",
        nombre: "bbbbbb",
        tipoDocumento: "CC",
        apellido: "ccccccc",
        fechaCreacion: "2021-12-14 13:04:03.111",
        contrasena: "",
        tipoUsuario: "E",
        numeroDocumento: "55555",
        email: "dfdf@sdsd.com",
      },
      {
        numeroCelular: "3215654789",
        estado: "A",
        roles: [
          {
            idRol: 2,
            estado: "A",
            nombreRol: "Usuario_Externo",
            fechaCreacion: "2021-11-07 10:56:06.0",
          },
        ],
        idUsuario: 22,
        nombreUsuario: "12345",
        nombre: "Luis",
        tipoDocumento: "CC",
        apellido: "Luises",
        fechaCreacion: "2021-12-06 15:48:12.71",
        contrasena: "",
        tipoUsuario: "E",
        numeroDocumento: "12345",
        email: "dtorres@dejsoftware.com",
      },
      {
        numeroCelular: "8000000000",
        image: "/uploads/user_default.svg",
        estado: "A",
        roles: [
          {
            idRol: 1,
            estado: "A",
            nombreRol: "Administrador",
            fechaCreacion: "2021-11-07 10:56:06.0",
          },
        ],
        idUsuario: 30,
        nombreUsuario: "1111111",
        nombre: "aaa",
        tipoDocumento: "CC",
        apellido: "aaa",
        fechaCreacion: "2023-02-10 20:03:01.152",
        contrasena: "",
        tipoUsuario: "I",
        numeroDocumento: "1111111",
        email: "aaa@aa.aaa",
      },
      {
        numeroCelular: "3106777777",
        estado: "A",
        roles: [
          {
            idRol: 2,
            estado: "A",
            nombreRol: "Usuario_Externo",
            fechaCreacion: "2021-11-07 10:56:06.0",
          },
        ],
        idUsuario: 17,
        nombreUsuario: "18129164",
        nombre: "Rigoberto",
        tipoDocumento: "CC",
        apellido: "Rios Hueso",
        fechaCreacion: "2021-11-17 15:58:50.223",
        contrasena: "",
        tipoUsuario: "E",
        numeroDocumento: "18129164",
        email: "rigoriosh@gmail.com",
      },
      {
        numeroCelular: "1234567891",
        image: "/path/to/imagen",
        estado: "A",
        roles: [
          {
            idRol: 1,
            estado: "A",
            nombreRol: "Administrador",
            fechaCreacion: "2021-11-07 10:56:06.0",
          },
        ],
        idUsuario: 1,
        nombreUsuario: "davids",
        nombre: "David Steven",
        ultimaFechaLogin: "2020-11-06 17:30:50.0",
        tipoDocumento: "CC",
        apellido: "Torres Figueroa",
        fechaCreacion: "2020-11-06 17:30:50.0",
        contrasena: "",
        tipoUsuario: "I",
        numeroDocumento: "1587411224",
        email: "davids182009@gmail.com",
      },
      {
        numeroCelular: "8000000",
        image: "/uploads/user_default.svg",
        estado: "A",
        roles: [
          {
            idRol: 1,
            estado: "A",
            nombreRol: "Administrador",
            fechaCreacion: "2021-11-07 10:56:06.0",
          },
        ],
        idUsuario: 7,
        nombreUsuario: "admin",
        nombre: "nombre usuario",
        tipoDocumento: "CC",
        apellido: "apellido usuario",
        fechaCreacion: "2021-11-10 21:45:47.518",
        contrasena: "",
        tipoUsuario: "I",
        numeroDocumento: "1234554221",
        email: "prueba@asomunicipios.com",
      },
      {
        numeroCelular: "3106777777",
        estado: "A",
        roles: [
          {
            idRol: 2,
            estado: "A",
            nombreRol: "Usuario_Externo",
            fechaCreacion: "2021-11-07 10:56:06.0",
          },
        ],
        idUsuario: 16,
        nombreUsuario: "78787878",
        nombre: "Rigoberto",
        tipoDocumento: "CC",
        apellido: "Rios Hueso",
        fechaCreacion: "2021-11-15 11:50:14.931",
        contrasena: "",
        tipoUsuario: "E",
        numeroDocumento: "78787878",
        email: "rigoriosh@gmail.com",
      },
      {
        numeroCelular: "1234567891",
        estado: "A",
        roles: [
          {
            idRol: 2,
            estado: "A",
            nombreRol: "Usuario_Externo",
            fechaCreacion: "2021-11-07 10:56:06.0",
          },
        ],
        idUsuario: 19,
        nombreUsuario: "123456789",
        nombre: "Thiago",
        tipoDocumento: "CE",
        apellido: "Rios",
        fechaCreacion: "2021-11-24 15:46:27.518",
        contrasena: "",
        tipoUsuario: "E",
        numeroDocumento: "123456789",
        email: "rigoriosh@gmail.com",
      },
      {
        numeroCelular: "8000000",
        estado: "A",
        roles: [
          {
            idRol: 2,
            estado: "A",
            nombreRol: "Usuario_Externo",
            fechaCreacion: "2021-11-07 10:56:06.0",
          },
        ],
        idUsuario: 8,
        nombreUsuario: "externo nuevo",
        nombre: "test nombre",
        tipoDocumento: "CC",
        apellido: "test apellido",
        fechaCreacion: "2021-11-14 12:34:10.653",
        contrasena: "",
        tipoUsuario: "E",
        numeroDocumento: "1285988664",
        email: "prueba@asomunicipios.com",
      },
    ],
  },
};